//! Trees the index stays out of.
//!
//! Indexing costs CPU per change event, not per entry: a cache that rewrites
//! itself all day means directory listings forever, while a large read-only
//! tree costs nothing at runtime. The default list is therefore about churn and
//! about paths nobody looks for by name, not about size.
//!
//! Rules are consulted before a directory is opened, so an ignored subtree is
//! never listed, never indexed, and never wakes the watcher. Add rules in
//! `<data dir>/ignore`; a `!` line takes a rule back, or carves a hole out of an
//! ignored tree.

use std::os::unix::ffi::OsStrExt;
use std::path::Path;
use std::sync::OnceLock;

/// Path rules: the whole subtree is ignored. `~/` is the home directory.
#[rustfmt::skip]
const DEFAULT_PATHS: &[&str] = &[
    // Our own state. Writing a content segment must not wake the watcher, which
    // would then list this directory and count our own files.
    "~/Library/Application Support/FSearch",
    // Caches, logs and app state: generated by apps, never searched by name.
    "~/Library/Caches", "~/Library/Logs", "~/Library/DiagnosticReports", "~/Library/Metadata",
    "~/Library/Saved Application State", "~/Library/HTTPStorages", "~/Library/WebKit",
    "/private/var/db", "/private/var/log", "/private/var/folders", "/private/tmp", "/tmp",
];

/// Name rules: any file or directory with this name, at any depth.
#[rustfmt::skip]
const DEFAULT_NAMES: &[&str] = &[
    ".DS_Store", ".Spotlight-V100", ".fseventsd", ".DocumentRevisions-V100", ".TemporaryItems",
    ".Trashes", ".Backups.backupdb", "DerivedData", "Caches", "Cache", "Code Cache", "GPUCache",
    "ShaderCache", "DawnCache", "Service Worker", "blob_storage", "IndexedDB",
];

/// Absolute path prefixes and single-segment names, plus the `!` exceptions.
#[derive(Default)]
struct Rules {
    paths: Vec<Vec<u8>>,
    names: Vec<Vec<u8>>,
    keep_paths: Vec<Vec<u8>>,
    keep_names: Vec<Vec<u8>>,
}

static RULES: OnceLock<Rules> = OnceLock::new();

/// Load the defaults plus the optional `ignore` file. Once per process: the
/// daemon is the only thing that walks the disk.
pub fn init(home: &Path, dir: &Path) {
    let home = home.as_os_str().as_bytes();
    let mut r = Rules::default();
    for p in DEFAULT_PATHS {
        r.add(parse(p, home).expect("default paths parse"));
    }
    for n in DEFAULT_NAMES {
        r.names.push(n.as_bytes().to_vec());
    }
    if let Ok(text) = std::fs::read_to_string(dir.join("ignore")) {
        for line in text.lines() {
            if let Some(rule) = parse(line, home) {
                r.add(rule);
            }
        }
    }
    let _ = RULES.set(r);
}

/// Does any rule exist at all? Callers use it to skip tracking paths.
pub fn active() -> bool {
    RULES.get().is_some_and(|r| !r.paths.is_empty() || !r.names.is_empty())
}

/// Is this directory (or anything under it) ignored?
pub fn blocks_dir(path: &[u8]) -> bool {
    RULES.get().is_some_and(|r| r.blocks_dir(path))
}

/// Is an entry with this name ignored, whatever directory it sits in?
pub fn blocks_name(name: &[u8]) -> bool {
    RULES.get().is_some_and(|r| r.blocks_name(name))
}

/// One rule: `(keep, pattern, is_path)`, or `None` for blanks and comments.
fn parse(line: &str, home: &[u8]) -> Option<(bool, Vec<u8>, bool)> {
    let line = line.trim();
    if line.is_empty() || line.starts_with('#') {
        return None;
    }
    let (keep, pat) = match line.strip_prefix('!') {
        Some(rest) => (true, rest.trim()),
        None => (false, line),
    };
    let pat = pat.trim_end_matches('/');
    if let Some(rest) = pat.strip_prefix("~/") {
        let mut p = home.to_vec();
        p.push(b'/');
        p.extend_from_slice(rest.as_bytes());
        return Some((keep, p, true));
    }
    if pat == "~" {
        return Some((keep, home.to_vec(), true));
    }
    if pat.starts_with('/') {
        return Some((keep, pat.as_bytes().to_vec(), true));
    }
    (!pat.is_empty()).then(|| (keep, pat.as_bytes().to_vec(), false))
}

/// `path` is `prefix` itself or sits under it.
fn under(path: &[u8], prefix: &[u8]) -> bool {
    path.starts_with(prefix) && path.get(prefix.len()).is_none_or(|&b| b == b'/')
}

fn base(path: &[u8]) -> &[u8] {
    match path.iter().rposition(|&b| b == b'/') {
        Some(i) => &path[i + 1..],
        None => path,
    }
}

impl Rules {
    fn add(&mut self, (keep, pat, is_path): (bool, Vec<u8>, bool)) {
        match (keep, is_path) {
            (false, true) => self.paths.push(pat),
            (false, false) => self.names.push(pat),
            (true, true) => self.keep_paths.push(pat),
            (true, false) => self.keep_names.push(pat),
        }
    }

    fn blocks_dir(&self, path: &[u8]) -> bool {
        // A kept path inside a blocked one means we still have to descend.
        if self.keep_paths.iter().any(|k| under(path, k) || under(k, path)) {
            return false;
        }
        let name = base(path);
        if self.keep_names.iter().any(|n| n == name) {
            return false;
        }
        self.paths.iter().any(|p| under(path, p)) || self.blocks_name(name)
    }

    fn blocks_name(&self, name: &[u8]) -> bool {
        if self.keep_names.iter().any(|n| n == name) {
            return false;
        }
        self.names.iter().any(|n| n == name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const HOME: &[u8] = b"/Users/x";

    fn rules(lines: &[&str]) -> Rules {
        let mut r = Rules::default();
        for p in DEFAULT_PATHS {
            r.add(parse(p, HOME).unwrap());
        }
        for n in DEFAULT_NAMES {
            r.names.push(n.as_bytes().to_vec());
        }
        for line in lines {
            if let Some(rule) = parse(line, HOME) {
                r.add(rule);
            }
        }
        r
    }

    #[test]
    fn paths_match_at_a_component_boundary() {
        let r = rules(&[]);
        assert!(r.blocks_dir(b"/private/var/log"));
        assert!(r.blocks_dir(b"/private/var/log/system.log"));
        assert!(!r.blocks_dir(b"/private/var/logs")); // prefix, not a parent
        assert!(!r.blocks_dir(b"/private/var"));
        assert!(r.blocks_dir(b"/tmp/scratch"));
    }

    #[test]
    fn home_prefixes_expand() {
        let r = rules(&[]);
        assert!(r.blocks_dir(b"/Users/x/Library/Caches/com.apple.Safari"));
        assert!(!r.blocks_dir(b"/Users/y/Library/Application Support/FSearch"));
    }

    #[test]
    fn names_match_at_any_depth_and_override_nothing_else() {
        let r = rules(&[]);
        assert!(r.blocks_dir(b"/Users/x/Library/Application Support/App/Caches"));
        assert!(!r.blocks_dir(b"/Users/x/Projects/app/node_modules")); // not a default rule
        assert!(r.blocks_name(b".DS_Store"));
        assert!(!r.blocks_name(b"DS_Store"));
    }

    #[test]
    fn a_kept_path_inside_an_ignored_tree_is_kept() {
        let r = rules(&["!~/Library/Caches/com.foo"]);
        assert!(!r.blocks_dir(b"/Users/x/Library/Caches/com.foo"));
        assert!(!r.blocks_dir(b"/Users/x/Library/Caches/com.foo/state"));
        assert!(!r.blocks_dir(b"/Users/x/Library/Caches")); // must descend
        assert!(r.blocks_dir(b"/Users/x/Library/Caches/other"));
    }

    #[test]
    fn comments_blanks_and_bare_names() {
        let r = rules(&["# a note", "", "  ", "~/work/scratch/", "node_modules", "!target"]);
        assert!(r.blocks_dir(b"/Users/x/work/scratch"));
        assert!(r.blocks_dir(b"/Users/x/work/scratch/x"));
        assert!(r.blocks_dir(b"/elsewhere/node_modules"));
        assert!(!r.blocks_dir(b"/Users/x/pkg/target")); // kept by `!target`
        assert_eq!(parse("# nope", HOME), None);
        assert_eq!(parse("   ", HOME), None);
    }

    #[test]
    fn nothing_is_blocked_before_init_or_for_the_root() {
        assert!(!Rules::default().blocks_dir(b"/tmp"));
        let r = rules(&[]);
        assert!(!r.blocks_dir(b"/"));
        assert!(!r.blocks_dir(b"/Users/x/Projects/fsearch/src/main.rs"));
    }
}
